### ISSUE TITLE
No sound on Arch Linux

### ISSUE THREAD

**Issue by jkkr2** [scivision/Adventure7#1]
Hi Michael, many thanks for providing Adventure 7 in Fortran 2008!
Compilation and installation went through smooth on gfortran 8.2. Game work nice but without sound. ffplay is working. testsound also not. I had to change the sounds-dir in sound.f90 in line 10 to
`sounddir='../sounds'` instead of just `sounds`. After new compiling, sound is working for me! :-)

Great fun!

ps offtopic: By what unlikely chance I read you atan, atan2 issue today at Intel's forum and at home just found by different interest Adventure and found you behind. A small world Fortran seems to be.

**Comment by scivision** [comment]
Thanks, this is fixed in d2b9371db9cec
